"""Cross-implementation check: the Python reference verifier must reproduce the Go test vectors exactly.
Run: python verifier/test_verify.py   (vectors: docs/test-vectors.json, generated by the Go tests)"""
import json, pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).parent))
import verify as v

V = json.load(open(pathlib.Path(__file__).parent.parent / "docs" / "test-vectors.json"))
assert v.receipt_id(V["receipt_id"]["drop_id"], bytes.fromhex(V["receipt_id"]["token_hex"])) == V["receipt_id"]["receipt_id"], "receipt id"
for c in V["cases"]:
    es, levels = v.build_levels([(e["receipt_id"], e["tier"]) for e in c["entries"]])
    root = v.root_of(levels, len(es))
    assert root.hex() == c["root"], ("root", len(es))
    beacon = bytes.fromhex(c["beacon"]) if c["beacon"] else None
    final = v.final_randomness(bytes.fromhex(c["seed"]), root, beacon)
    assert final.hex() == c["final"], "final"
    by = {}
    for r, t in es: by.setdefault(t, []).append(r)
    for t in c["tiers"]:
        assert v.order(final, by[t["tier"]]) == t["order"], ("order", t["tier"])
    i = c["proof_index"]
    assert v.proof(levels, i) == c["proof"], "proof path"
    assert v.verify_proof(es[i][0], es[i][1], c["proof"], c["root"])
    assert not v.verify_proof(es[i][0], "other", c["proof"], c["root"])
print(f"python verifier matches Go on {len(V['cases'])} vectors")
